name: aieco_mesh
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.6+116

environment:
  sdk: ^3.12.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  webview_flutter: ^4.13.1
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/launch_fullscreen.png
    - assets/images/hong_kong_18_districts.jpg
    - assets/images/districts/
    - assets/map_tiles/hong_kong/README.txt
    - assets/map_tiles/hong_kong/10/835/
    - assets/map_tiles/hong_kong/10/836/
    - assets/map_tiles/hong_kong/10/837/
    - assets/map_tiles/hong_kong/11/1671/
    - assets/map_tiles/hong_kong/11/1672/
    - assets/map_tiles/hong_kong/11/1673/
    - assets/map_tiles/hong_kong/11/1674/
    - assets/map_tiles/hong_kong/11/1675/
    - assets/map_tiles/hong_kong/12/3342/
    - assets/map_tiles/hong_kong/12/3343/
    - assets/map_tiles/hong_kong/12/3344/
    - assets/map_tiles/hong_kong/12/3345/
    - assets/map_tiles/hong_kong/12/3346/
    - assets/map_tiles/hong_kong/12/3347/
    - assets/map_tiles/hong_kong/12/3348/
    - assets/map_tiles/hong_kong/12/3349/
    - assets/map_tiles/hong_kong/12/3350/
    - assets/map_tiles/hong_kong/13/6685/
    - assets/map_tiles/hong_kong/13/6686/
    - assets/map_tiles/hong_kong/13/6687/
    - assets/map_tiles/hong_kong/13/6688/
    - assets/map_tiles/hong_kong/13/6689/
    - assets/map_tiles/hong_kong/13/6690/
    - assets/map_tiles/hong_kong/13/6691/
    - assets/map_tiles/hong_kong/13/6692/
    - assets/map_tiles/hong_kong/13/6693/
    - assets/map_tiles/hong_kong/13/6694/
    - assets/map_tiles/hong_kong/13/6695/
    - assets/map_tiles/hong_kong/13/6696/
    - assets/map_tiles/hong_kong/13/6697/
    - assets/map_tiles/hong_kong/13/6698/
    - assets/map_tiles/hong_kong/13/6699/
    - assets/map_tiles/hong_kong/13/6700/
    - assets/map_tiles/hong_kong/13/6701/
    - assets/map_tiles/hong_kong/14/13371/
    - assets/map_tiles/hong_kong/14/13372/
    - assets/map_tiles/hong_kong/14/13373/
    - assets/map_tiles/hong_kong/14/13374/
    - assets/map_tiles/hong_kong/14/13375/
    - assets/map_tiles/hong_kong/14/13376/
    - assets/map_tiles/hong_kong/14/13377/
    - assets/map_tiles/hong_kong/14/13378/
    - assets/map_tiles/hong_kong/14/13379/
    - assets/map_tiles/hong_kong/14/13380/
    - assets/map_tiles/hong_kong/14/13381/
    - assets/map_tiles/hong_kong/14/13382/
    - assets/map_tiles/hong_kong/14/13383/
    - assets/map_tiles/hong_kong/14/13384/
    - assets/map_tiles/hong_kong/14/13385/
    - assets/map_tiles/hong_kong/14/13386/
    - assets/map_tiles/hong_kong/14/13387/
    - assets/map_tiles/hong_kong/14/13388/
    - assets/map_tiles/hong_kong/14/13389/
    - assets/map_tiles/hong_kong/14/13390/
    - assets/map_tiles/hong_kong/14/13391/
    - assets/map_tiles/hong_kong/14/13392/
    - assets/map_tiles/hong_kong/14/13393/
    - assets/map_tiles/hong_kong/14/13394/
    - assets/map_tiles/hong_kong/14/13395/
    - assets/map_tiles/hong_kong/14/13396/
    - assets/map_tiles/hong_kong/14/13397/
    - assets/map_tiles/hong_kong/14/13398/
    - assets/map_tiles/hong_kong/14/13399/
    - assets/map_tiles/hong_kong/14/13400/
    - assets/map_tiles/hong_kong/14/13401/
    - assets/map_tiles/hong_kong/14/13402/
    - assets/map_tiles/hong_kong/14/13403/
    - assets/map_tiles/hong_kong/15/26742/
    - assets/map_tiles/hong_kong/15/26743/
    - assets/map_tiles/hong_kong/15/26744/
    - assets/map_tiles/hong_kong/15/26745/
    - assets/map_tiles/hong_kong/15/26746/
    - assets/map_tiles/hong_kong/15/26747/
    - assets/map_tiles/hong_kong/15/26748/
    - assets/map_tiles/hong_kong/15/26749/
    - assets/map_tiles/hong_kong/15/26750/
    - assets/map_tiles/hong_kong/15/26751/
    - assets/map_tiles/hong_kong/15/26752/
    - assets/map_tiles/hong_kong/15/26753/
    - assets/map_tiles/hong_kong/15/26754/
    - assets/map_tiles/hong_kong/15/26755/
    - assets/map_tiles/hong_kong/15/26756/
    - assets/map_tiles/hong_kong/15/26757/
    - assets/map_tiles/hong_kong/15/26758/
    - assets/map_tiles/hong_kong/15/26759/
    - assets/map_tiles/hong_kong/15/26760/
    - assets/map_tiles/hong_kong/15/26761/
    - assets/map_tiles/hong_kong/15/26762/
    - assets/map_tiles/hong_kong/15/26763/
    - assets/map_tiles/hong_kong/15/26764/
    - assets/map_tiles/hong_kong/15/26765/
    - assets/map_tiles/hong_kong/15/26766/
    - assets/map_tiles/hong_kong/15/26767/
    - assets/map_tiles/hong_kong/15/26768/
    - assets/map_tiles/hong_kong/15/26769/
    - assets/map_tiles/hong_kong/15/26770/
    - assets/map_tiles/hong_kong/15/26771/
    - assets/map_tiles/hong_kong/15/26772/
    - assets/map_tiles/hong_kong/15/26773/
    - assets/map_tiles/hong_kong/15/26774/
    - assets/map_tiles/hong_kong/15/26775/
    - assets/map_tiles/hong_kong/15/26776/
    - assets/map_tiles/hong_kong/15/26777/
    - assets/map_tiles/hong_kong/15/26778/
    - assets/map_tiles/hong_kong/15/26779/
    - assets/map_tiles/hong_kong/15/26780/
    - assets/map_tiles/hong_kong/15/26781/
    - assets/map_tiles/hong_kong/15/26782/
    - assets/map_tiles/hong_kong/15/26783/
    - assets/map_tiles/hong_kong/15/26784/
    - assets/map_tiles/hong_kong/15/26785/
    - assets/map_tiles/hong_kong/15/26786/
    - assets/map_tiles/hong_kong/15/26787/
    - assets/map_tiles/hong_kong/15/26788/
    - assets/map_tiles/hong_kong/15/26789/
    - assets/map_tiles/hong_kong/15/26790/
    - assets/map_tiles/hong_kong/15/26791/
    - assets/map_tiles/hong_kong/15/26792/
    - assets/map_tiles/hong_kong/15/26793/
    - assets/map_tiles/hong_kong/15/26794/
    - assets/map_tiles/hong_kong/15/26795/
    - assets/map_tiles/hong_kong/15/26796/
    - assets/map_tiles/hong_kong/15/26797/
    - assets/map_tiles/hong_kong/15/26798/
    - assets/map_tiles/hong_kong/15/26799/
    - assets/map_tiles/hong_kong/15/26800/
    - assets/map_tiles/hong_kong/15/26801/
    - assets/map_tiles/hong_kong/15/26802/
    - assets/map_tiles/hong_kong/15/26803/
    - assets/map_tiles/hong_kong/15/26804/
    - assets/map_tiles/hong_kong/15/26805/
    - assets/map_tiles/hong_kong/15/26806/
    - assets/map_tiles/hong_kong/15/26807/
    - assets/map_tiles/hong_kong/16/53484/
    - assets/map_tiles/hong_kong/16/53485/
    - assets/map_tiles/hong_kong/16/53486/
    - assets/map_tiles/hong_kong/16/53487/
    - assets/map_tiles/hong_kong/16/53488/
    - assets/map_tiles/hong_kong/16/53489/
    - assets/map_tiles/hong_kong/16/53490/
    - assets/map_tiles/hong_kong/16/53491/
    - assets/map_tiles/hong_kong/16/53492/
    - assets/map_tiles/hong_kong/16/53493/
    - assets/map_tiles/hong_kong/16/53494/
    - assets/map_tiles/hong_kong/16/53495/
    - assets/map_tiles/hong_kong/16/53496/
    - assets/map_tiles/hong_kong/16/53497/
    - assets/map_tiles/hong_kong/16/53498/
    - assets/map_tiles/hong_kong/16/53499/
    - assets/map_tiles/hong_kong/16/53500/
    - assets/map_tiles/hong_kong/16/53501/
    - assets/map_tiles/hong_kong/16/53502/
    - assets/map_tiles/hong_kong/16/53503/
    - assets/map_tiles/hong_kong/16/53504/
    - assets/map_tiles/hong_kong/16/53505/
    - assets/map_tiles/hong_kong/16/53506/
    - assets/map_tiles/hong_kong/16/53507/
    - assets/map_tiles/hong_kong/16/53508/
    - assets/map_tiles/hong_kong/16/53509/
    - assets/map_tiles/hong_kong/16/53510/
    - assets/map_tiles/hong_kong/16/53511/
    - assets/map_tiles/hong_kong/16/53512/
    - assets/map_tiles/hong_kong/16/53513/
    - assets/map_tiles/hong_kong/16/53514/
    - assets/map_tiles/hong_kong/16/53515/
    - assets/map_tiles/hong_kong/16/53516/
    - assets/map_tiles/hong_kong/16/53517/
    - assets/map_tiles/hong_kong/16/53518/
    - assets/map_tiles/hong_kong/16/53519/
    - assets/map_tiles/hong_kong/16/53520/
    - assets/map_tiles/hong_kong/16/53521/
    - assets/map_tiles/hong_kong/16/53522/
    - assets/map_tiles/hong_kong/16/53523/
    - assets/map_tiles/hong_kong/16/53524/
    - assets/map_tiles/hong_kong/16/53525/
    - assets/map_tiles/hong_kong/16/53526/
    - assets/map_tiles/hong_kong/16/53527/
    - assets/map_tiles/hong_kong/16/53528/
    - assets/map_tiles/hong_kong/16/53529/
    - assets/map_tiles/hong_kong/16/53530/
    - assets/map_tiles/hong_kong/16/53531/
    - assets/map_tiles/hong_kong/16/53532/
    - assets/map_tiles/hong_kong/16/53533/
    - assets/map_tiles/hong_kong/16/53534/
    - assets/map_tiles/hong_kong/16/53535/
    - assets/map_tiles/hong_kong/16/53536/
    - assets/map_tiles/hong_kong/16/53537/
    - assets/map_tiles/hong_kong/16/53538/
    - assets/map_tiles/hong_kong/16/53539/
    - assets/map_tiles/hong_kong/16/53540/
    - assets/map_tiles/hong_kong/16/53541/
    - assets/map_tiles/hong_kong/16/53542/
    - assets/map_tiles/hong_kong/16/53543/
    - assets/map_tiles/hong_kong/16/53544/
    - assets/map_tiles/hong_kong/16/53545/
    - assets/map_tiles/hong_kong/16/53546/
    - assets/map_tiles/hong_kong/16/53547/
    - assets/map_tiles/hong_kong/16/53548/
    - assets/map_tiles/hong_kong/16/53549/
    - assets/map_tiles/hong_kong/16/53550/
    - assets/map_tiles/hong_kong/16/53551/
    - assets/map_tiles/hong_kong/16/53552/
    - assets/map_tiles/hong_kong/16/53553/
    - assets/map_tiles/hong_kong/16/53554/
    - assets/map_tiles/hong_kong/16/53555/
    - assets/map_tiles/hong_kong/16/53556/
    - assets/map_tiles/hong_kong/16/53557/
    - assets/map_tiles/hong_kong/16/53558/
    - assets/map_tiles/hong_kong/16/53559/
    - assets/map_tiles/hong_kong/16/53560/
    - assets/map_tiles/hong_kong/16/53561/
    - assets/map_tiles/hong_kong/16/53562/
    - assets/map_tiles/hong_kong/16/53563/
    - assets/map_tiles/hong_kong/16/53564/
    - assets/map_tiles/hong_kong/16/53565/
    - assets/map_tiles/hong_kong/16/53566/
    - assets/map_tiles/hong_kong/16/53567/
    - assets/map_tiles/hong_kong/16/53568/
    - assets/map_tiles/hong_kong/16/53569/
    - assets/map_tiles/hong_kong/16/53570/
    - assets/map_tiles/hong_kong/16/53571/
    - assets/map_tiles/hong_kong/16/53572/
    - assets/map_tiles/hong_kong/16/53573/
    - assets/map_tiles/hong_kong/16/53574/
    - assets/map_tiles/hong_kong/16/53575/
    - assets/map_tiles/hong_kong/16/53576/
    - assets/map_tiles/hong_kong/16/53577/
    - assets/map_tiles/hong_kong/16/53578/
    - assets/map_tiles/hong_kong/16/53579/
    - assets/map_tiles/hong_kong/16/53580/
    - assets/map_tiles/hong_kong/16/53581/
    - assets/map_tiles/hong_kong/16/53582/
    - assets/map_tiles/hong_kong/16/53583/
    - assets/map_tiles/hong_kong/16/53584/
    - assets/map_tiles/hong_kong/16/53585/
    - assets/map_tiles/hong_kong/16/53586/
    - assets/map_tiles/hong_kong/16/53587/
    - assets/map_tiles/hong_kong/16/53588/
    - assets/map_tiles/hong_kong/16/53589/
    - assets/map_tiles/hong_kong/16/53590/
    - assets/map_tiles/hong_kong/16/53591/
    - assets/map_tiles/hong_kong/16/53592/
    - assets/map_tiles/hong_kong/16/53593/
    - assets/map_tiles/hong_kong/16/53594/
    - assets/map_tiles/hong_kong/16/53595/
    - assets/map_tiles/hong_kong/16/53596/
    - assets/map_tiles/hong_kong/16/53597/
    - assets/map_tiles/hong_kong/16/53598/
    - assets/map_tiles/hong_kong/16/53599/
    - assets/map_tiles/hong_kong/16/53600/
    - assets/map_tiles/hong_kong/16/53601/
    - assets/map_tiles/hong_kong/16/53602/
    - assets/map_tiles/hong_kong/16/53603/
    - assets/map_tiles/hong_kong/16/53604/
    - assets/map_tiles/hong_kong/16/53605/
    - assets/map_tiles/hong_kong/16/53606/
    - assets/map_tiles/hong_kong/16/53607/
    - assets/map_tiles/hong_kong/16/53608/
    - assets/map_tiles/hong_kong/16/53609/
    - assets/map_tiles/hong_kong/16/53610/
    - assets/map_tiles/hong_kong/16/53611/
    - assets/map_tiles/hong_kong/16/53612/
    - assets/map_tiles/hong_kong/16/53613/
    - assets/map_tiles/hong_kong/16/53614/
    - assets/map_tiles/hong_kong/16/53615/
    - assets/map_tiles/hong_kong/17/107085/
    - assets/map_tiles/hong_kong/17/107086/
    - assets/map_tiles/hong_kong/17/107087/
    - assets/map_tiles/hong_kong/17/107088/
    - assets/map_tiles/hong_kong/17/107089/
    - assets/map_tiles/hong_kong/17/107090/
    - assets/map_tiles/hong_kong/17/107091/
    - assets/map_tiles/hong_kong/17/107092/
    - assets/map_tiles/hong_kong/17/107093/
    - assets/map_tiles/hong_kong/17/107094/
    - assets/map_tiles/hong_kong/17/107095/
    - assets/map_tiles/hong_kong/17/107096/
    - assets/map_tiles/hong_kong/17/107097/
    - assets/map_tiles/hong_kong/17/107098/
    - assets/map_tiles/hong_kong/17/107099/
    - assets/map_tiles/hong_kong/17/107100/
    - assets/map_tiles/hong_kong/17/107101/
    - assets/map_tiles/hong_kong/17/107102/
    - assets/map_tiles/hong_kong/17/107103/
    - assets/map_tiles/hong_kong/17/107104/
    - assets/map_tiles/hong_kong/17/107105/
    - assets/map_tiles/hong_kong/17/107106/
    - assets/map_tiles/hong_kong/17/107107/
    - assets/map_tiles/hong_kong/17/107108/
    - assets/map_tiles/hong_kong/17/107109/
    - assets/map_tiles/hong_kong/17/107110/
    - assets/map_tiles/hong_kong/17/107111/
    - assets/map_tiles/hong_kong/17/107112/
    - assets/map_tiles/hong_kong/17/107113/
    - assets/map_tiles/hong_kong/17/107114/
    - assets/map_tiles/hong_kong/17/107115/
    - assets/map_tiles/hong_kong/17/107116/
    - assets/map_tiles/hong_kong/17/107117/
    - assets/map_tiles/hong_kong/17/107118/
    - assets/map_tiles/hong_kong/17/107119/
    - assets/map_tiles/hong_kong/17/107120/
    - assets/map_tiles/hong_kong/17/107121/
    - assets/map_tiles/hong_kong/17/107122/
    - assets/map_tiles/hong_kong/17/107123/
    - assets/map_tiles/hong_kong/17/107124/
    - assets/map_tiles/hong_kong/17/107125/
    - assets/map_tiles/hong_kong/17/107126/
    - assets/map_tiles/hong_kong/17/107127/
    - assets/map_tiles/hong_kong/17/107128/
    - assets/map_tiles/hong_kong/17/107129/
    - assets/map_tiles/hong_kong/17/107130/
    - assets/map_tiles/hong_kong/17/107131/
    - assets/map_tiles/hong_kong/17/107132/
    - assets/map_tiles/hong_kong/17/107133/
    - assets/map_tiles/hong_kong/17/107134/
    - assets/map_tiles/hong_kong/17/107135/
    - assets/map_tiles/hong_kong/17/107136/
    - assets/map_tiles/hong_kong/17/107137/
    - assets/map_tiles/hong_kong/17/107138/
    - assets/map_tiles/hong_kong/17/107139/
    - assets/map_tiles/hong_kong/17/107140/
    - assets/map_tiles/hong_kong/18/214215/
    - assets/map_tiles/hong_kong/18/214216/
    - assets/map_tiles/hong_kong/18/214217/
    - assets/map_tiles/hong_kong/18/214218/
    - assets/map_tiles/hong_kong/18/214219/
    - assets/map_tiles/hong_kong/18/214220/
    - assets/map_tiles/hong_kong/18/214221/
    - assets/map_tiles/hong_kong/18/214222/
    - assets/map_tiles/hong_kong/18/214223/
    - assets/map_tiles/hong_kong/18/214224/
    - assets/map_tiles/hong_kong/18/214225/
    - assets/map_tiles/hong_kong/18/214226/
    - assets/map_tiles/hong_kong/18/214227/
    - assets/map_tiles/hong_kong/18/214228/
    - assets/map_tiles/hong_kong/18/214229/
    - assets/map_tiles/hong_kong/18/214230/
    - assets/map_tiles/hong_kong/18/214231/
    - assets/map_tiles/hong_kong/18/214232/
    - assets/map_tiles/hong_kong/18/214233/
    - assets/map_tiles/hong_kong/18/214234/
    - assets/map_tiles/hong_kong/18/214235/
    - assets/map_tiles/hong_kong/18/214236/
    - assets/map_tiles/hong_kong/18/214237/
    - assets/map_tiles/hong_kong/18/214238/
    - assets/map_tiles/hong_kong/18/214239/
    - assets/map_tiles/hong_kong/18/214240/
    - assets/map_tiles/hong_kong/18/214241/
    - assets/map_tiles/hong_kong/18/214242/
    - assets/map_tiles/hong_kong/18/214243/
    - assets/map_tiles/hong_kong/18/214244/
    - assets/map_tiles/hong_kong/18/214245/
    - assets/map_tiles/hong_kong/18/214246/
    - assets/map_tiles/hong_kong/18/214247/
    - assets/map_tiles/hong_kong/18/214248/
    - assets/map_tiles/hong_kong/18/214249/
    - assets/map_tiles/hong_kong/18/214250/
    - assets/map_tiles/hong_kong/18/214251/
    - assets/map_tiles/hong_kong/18/214252/
    - assets/map_tiles/hong_kong/18/214253/
    - assets/map_tiles/hong_kong/18/214254/
    - assets/map_tiles/hong_kong/18/214255/
    - assets/map_tiles/hong_kong/18/214256/
    - assets/map_tiles/hong_kong/18/214257/
    - assets/map_tiles/hong_kong/18/214258/
    - assets/map_tiles/hong_kong/18/214259/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
